### ISSUE TITLE
Do not generate test for a free site if contact map says the site cannot be bound

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#112]
A(x~p) -> ... 
... -> A(x~p) 

are not true test or requirement for x to be free if x has no possible partner.

**Comment by pirbo** [comment]
Done

**Comment by vd1** [comment]
Do you check that the site is not bound in the initial state?


If I remember correctly, in KaSa's ancestor (complx) Jerome had implemented
a concept of compression of rules chopping off tests that were provably
redundant.
This was based on a static analysis of reachability,
and was producing invariants (relative to initial state)
and doing this simplification automatically.

V.

**Comment by pirbo** [comment]
We ask KaSa for the contact map. If being free is the only state a site can have, we remove the tests to free.
For now, the contact map given by KaSa is purely syntactical so a test is removed if neither the initial state nor any rule nor any perturbation mention the site in an other state than free.
Indeed, when the information given by KaSa will be improve to reduce the field of accessible states, the code should take advantage automatically of that in order to improve even more the compilation.
