### ISSUE TITLE
deadlock bug ?

### ISSUE THREAD

**Issue by macavali** [Kappa-Dev/KaSim#117]
Hi
I was trying to run the code below.  My understanding is that  A(s1~p?) means that site s1 is either bound or unbound and has state p.  However when I try to run it I get a deadlock error.

many thanks

-----------
%agent: A(s1~u~p)
%agent: B(s1)

A(s1~p?),B(s1)-> A(s1~p!1),B(s1!1)@'rate'

%var: 'rate' 100

%obs: 'A_B' A(s1!1),B(s1!1)

%init: 1 A(s1)
%init: 1000 B(s1) 
--------------------

**Comment by vd1** [comment]
try with this:

%init: 1 A(s1~p)

i guess the default expansion of KaSim is the first symbol in the
enumeration so:

%init: 1 A(s1)

really means

%init: 1 A(s1~u)

which deadlocks

**Comment by vd1** [comment]
My turn to ask a question: your rule

A(s1~p?),B(s1)-> A(s1~p!1),B(s1!1)@'rate'

is meant to be semantically equivalent to

A(s1~p),B(s1)-> A(s1~p!1),B(s1!1)@'rate'

?

Or did you mean that the you can pick a
bound A and plug into a fresh free B?

**Comment by pirbo** [comment]
You're right @vd1 the first internal state is the internal state by default so A(s1) means indeed A(s1~u) in the example.

In KaSim4, A(s1~p?),B(s1)-> A(s1~p!1),B(s1!1)@'rate' will be equivalent to
A(s1~p),B(s1)-> A(s1~p!1),B(s1!1)@'rate'
AND
A(s1~p!1),B(s1),B(s1!1) -> A(s1~p!1),B(s1!1),B(s1) @'rate'
Have you got an opinion on that ?

**Comment by feret** [comment]
As far as I am concerned, I agree. 


-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by vd1** [comment]
it seems a natural understanding of the rule; what about this one

A(s?),B(s?)-> A(s!1),B(s!1)

if I follow the idea, the semantics is:
- find an A and a B
- disconnect their s sites (if there is need)
- connect them on s
which includes a a subcase the identity rule where A and B are already
connected on s?

[causally it is not really the identity but in DPO style:
A(s!1),B(s!1) <- A(s),B(s) -> A(s!1),B(s!1)]

**Comment by feret** [comment]
I mostly agree.

Note that in the SPO semantics this is really the identity rule (the domain of the rule has to be maximal to ensure uniqueness of pushout up to iso). 
Mimicking the SPO semantics, I would put more context in the action-based operational semantics: 
  - find an A and a B 
     * If A and B are connected together: do nothing
     * else 
	- find an A and a B 
        - disconnect their s sites (if there is need)
        - connect them on s

I find it a bit stange that the DPO observes different instances of the same link along a trace, whereas Kappa is assumed not to track this. 

But all of this does not really matter since all these interpretations have the same effect on the traces. 

Cheers. 
Jerome.
-------------------------

Jerome Feret
DI - Ecole Normale Superieure
45, rue d'Ulm
75230 Paris Cedex 5

phone: +33 1 44 32 37 66
fax  : +33 1 44 32 21 51
mail : feret@ens.fr

**Comment by vd1** [comment]
On 19 September 2015 at 12:36, Jérôme Feret <notifications@github.com>
wrote:

> Mimicking the SPO semantics, I would put more context in the action-based
> operational semantics:
> - find an A and a B
> * If A and B are connected together: do nothing
> * else
> - find an A and a B
> - disconnect their s sites (if there is need)
> - connect them on s
>

cute!
