### ISSUE TITLE
WebSim REST API improvements

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#161]
I will collect some suggestions about improving and API here.

1) I think that choice of 8080 is not optimal as it is very common port that is used by many webapplications so users may have a port conflict with something else.

2) swagger.json has some small errors, check editor.swagger like : 
``` 
✖ YAML Syntax Error
Missed comma between flow collection entries at line 60, column 22: }r ^ 
```
and 
```
Reference could not be resolved: #Plot
```
As people like me often use swagger editor for exploring API it would be nice to fix it.

3) Is GET /parse actually working? I am exploring it with swagger ui and when I send corrupted abc.ka it returns an array with an empty string instead of an error message (same that it does for a right model). Maybe I use it in a wrong way by giving it the whole model?

4) You have petstore.swagger.wordnik.com in swagger json, I think something like localhost:8080/v1 or some address of online websim will be better

5) For POST process I should get an array of tokens but I get token of Int. If you want to give an array it should be [token] I also do not thin that using int-s for tokens is a good idea, what about GUID ?

6) Not sure that POST process is a good name of starting a simulation. Something like /run or /start or /launch will be more natural

7) /process/ returns only list of all tokens. For UI clients it would be nice to be able to display a list of all running simulations with short info about event and time percentage. I think somethings like /process/all with array of short states of all simulations ( like name, event, event-percentage, time , etc) can be nice, from it UI clients will generate progress bars. Sometimes it is also not important to have life data from models, so if there is constantly updated list of processes then some apps will monitor it and will get plots for the simulations that have just finished.

8)

P.S. Should we make a separate label for WebSim ?

**Comment by pirbo** [comment]
1/ is now 5453 (This port is reserved by nobody according to /etc/services)
2/ I don't see the first error. I've fixed the second
4/ Indeed
PS/ done

**Comment by pirbo** [comment]
3/ Do you encodeURI() correctly the model ?
If I do not I have indeed very weird results but if I send ```%25agent:%20A(x)%0A%25agent:b(y,z,y)```
I receive indeed
```
HTTP/1.1  
Content-Type: application/json
["Error at line 2, characters 13-14: : Label 'y' already defined"]
```

**Comment by majorseitan** [comment]
1. Please don't change the default websim is a web application so it should default to this port - lets stick to conventions not create new ones.  If there is a conflict the port can be changed via the --port flag.  
5. This is mistake on my part and it has been fixed.
     The standard guid algorithm requires a mac address not always available.

**Comment by antonkulaga** [comment]
@pirbo 
for 3: I will check it once again. I think that maybe it will make sense to have POST instead of get here? The model can be quite long

@majorseitan 
for 2: there are implementations of GUID without MAC addresses. In general I just prefer having something unique instead of ints because with ints sometimes people have nameclashes (for instance if the server will crash it may start counting tokens from zero again and it will be harder to reference old simulation results)

**Comment by antonkulaga** [comment]
What is UnaryDistances array?

**Comment by pirbo** [comment]
1 -> 5 have been addressed.
6 is a matter of taste and I don't think that it is relevant. (feel free to open an independent issue if you really want to argue on that)
7 is a mix of a lot of different things.
- Yes GET /process/{token} should not send back all the information it has on the simulation but only the status (running/finished/errored, current biological time, nb of event triggered) and there must be some different requests to get the plot, the log, the stories, the snapshots, ...
- Because of network latency receiving a huge reply with too much information is sometime more efficient than making a lot of request to get exactly what you need. Therefore, keeping a request that send back all the available information on a simulation is still useful
- I would like to say that GET /process/all is useless because it is the sum of GET /process/ and all the GET /process/{returned token}/ but because of what I just said, there might be some advantage at having it. Never the less, in term of a shared online services, allowing every one to list all the process of everybody is a huge security problem and GET /process/ must not stay as it is so this consideration is postponed...

I close this issue and propose that you reopen more atomic one for the 2 last points if you think that it require more discussion.

**Comment by antonkulaga** [comment]
@pirbo you are right, I will open several small issues.
