### ISSUE TITLE
Release WebSim

### ISSUE THREAD

**Issue by antonkulaga** [Kappa-Dev/KaSim#222]
I sometimes ask people to install kappa-notebook locally and as it uses WebSim they face the problem of building the binaries for their OS. It would be nice to have a release of WebSim somewhere in https://github.com/Kappa-Dev/KaSim/releases for Linux/Windows/MacOS so I will just give them a download link for the WebSim

**Comment by pirbo** [comment]
Hi,
WebSim won't be available under windows in the near futur: the libraries it relies on do not compile under windows and their authors do not plan to make that happen!
There are now nightly-builds made under ubuntu14.04 (available with others at http://www.kappalanguage.org/nightly-builds/) BUT I doubt they'll work out of the box of anybody because it relies on special c libraries:
> ldd bin/WebSim
        linux-vdso.so.1 =>  (0x00007ffd545ac000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe1b7d18000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe1b7ab9000)
        libev.so.4 => /usr/lib/x86_64-linux-gnu/libev.so.4 (0x00007fe1b78ab000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe1b768d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe1b7387000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe1b7183000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe1b6dbe000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe1b80f4000)

**Comment by pirbo** [comment]
opam is amazing :-) I've managed to remove the dependency to libcrypto, libssl and libev so I consider this issue closed. (MacOS nightly builds are still to be done but this is not WebSim specific)
