### ISSUE TITLE
KaJaSim does not flag identical rule / variable names as error

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#225]
The following code is accepted and run by the Kappa Javascript simulator:
```
%agent: A()
'A+' -> A() @ 1
'A+' A() -> @ 1
%obs: 'A+' |A()|
```
Notice both rules have the same name, which itself is the same as the observable's label.

The log states everything passed.
```
+ Building initial simulation conditions...
	 -simulation parameters
	 -variable declarations
	 -rules
	 -perturbations
	 -observables
	 -initial conditions
	 Done

```

**Comment by pirbo** [comment]
Redefining a variable is a common practice in programming language. Therefore, I would find awkward to forbid it in the language of algebraic variables in Kappa. (In other word, I find redefinition legitimate for ```%var:```)

Now comes the case of ```%plot:```. Indeed, if you ask for the value of something called 'A' and later in the file redefined 'A' as something else, you can get lost in what the 'A' you're plotting stands for ... Forbidden to redefine 'A' is a too severe restriction to avoid this situation according to me but I don't see an obvious alternative.
(I'm just having the crazy idea that maybe ```%plot: 'A'``` should print the value of the last definition of 'A' in the file but this makes ```%obs:``` either not syntactic sugar for ```%var```: + ```%plot:``` anymore or EXTREMELY weird...

It is somehow the same for rule names: KaSim don't care about rule names, they are even optional! They're only used for human readable outputs. If a humain calls several things the same, it's not the system problem :-) (Now that I think about it, I wonder whether stories that recognize rules by their names can be disturbed by that, @feret? )
Anyway, as there is no "useful" mechanisms of overwriting a rule is by defining a second rule with the same name, I'm OK to add a 'sanity' check that rule names are unique.

**Comment by hmedina** [comment]
For redefining something, in the case where the first usage is not used, I
usually see a warning (MatLab for sure, OCaml I think...). If I reassign a
previously used label to another rule, then the first usage might go
unused, which should trigger a warning maybe? What usage could there be for
having two rules named the same?

I feel this is the point where an IDE should try to prevent the user from
doing useless things (like forgetting to use unique labels for rules), and
issue a warning. As for %var, I agree there is functionality in being able
to redefine ad hoc the variable. This however would mean different
treatment for variable names than for rule names.

**Comment by feret** [comment]
Dear Pierre, dear Hector,

As far as I remember, two rules with the same names used to be forbidden. 

Conflicts between rule/obs names in stories, will be dealt with the following way:
  -> For all the computation of the story, no problem, we use the unique id of rules. 
  -> Yet, there are two places where the name matters: 
             -> Graphical rendering
             -> Canonical form
        (The canonical form relies on the graphical rendering, and that is an intended feature: not a bug.  The main reason is that if two stories that would look the same but that would differ only in their internal representation, were displayed as two different stories, then, I would have a lot of end-user complains to ask me why these two stories have not be considered as one). 

If we want a more consistent way of dealing with conflicts between rule/obs names. 
We could improve the labelling function (that generates the string), by putting the loc of the rule declaration in case of conflict. 

Also with respect to variable redefinition, it worth noting that as far as I understand, variables are imperative (their value is evaluated at run-time).
This is an important feature so that we can update the value of a variable by the means of a perturbation. 
The usefulness of having several definitions of a variable value not inside  a perturbation is less clear to me. 
Indeed declaring a variable and changing its value can be seen as two different semantics operations (with this perspective, declaration is unique, but the value can be redefined (in a type consistent way, if types matter). 
Whatever, it is important to clearly explain the semantics (which value wins), all the more so since we may have multiple input files. 

In programming languages, either variables definitions are unique (which does not means that you cannot change their value), or you have scope rules. 
Here are I have the feeling that we are somewhere in the middle…

Cheers.
Jérôme.
