### ISSUE TITLE
contact map only displays rule-mentioned sites & agents

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#229]
For the Kappa Javascript simulator, the contact map is only displaying that which is mentioned in rules. Agents or sites declared but un-used are not displayed. If this is intended behavior, there ought to be a toggle box to render everything, only binding sites, or only mentioned binding sites. For example, the code:

```
%agent: A(x,y)
%agent: B(x,y)
%agent: C(x,y)
'r1' A(x),A(y) <-> A(x!1),A(y!1) @ 1,1
'r2' B(x),B(x) <-> B(x!1),B(x!1) @ 1,1
%obs: 'B' |B()|
```

Produces the below contact map.
![capture](https://cloud.githubusercontent.com/assets/1588553/15101091/04903f16-1555-11e6-8fb1-e3b282293962.PNG)

**Comment by feret** [comment]
I imagine that you use KaSa contact map, provided by the export module.
It would be great to use non oriented links, and to mention self-bond as well (for B.x).

We can, I think, consider 10 kinds of contact maps.
 - One checkable box to hide/show state site (implemented in KaSa, not exported yet)
 - One checkable box to consider or not the lhs of rules (not yet implemented in KaSa, but one line of code, export not difficult)
 - One three values option for: 
       1) take into account agent declaration + rhs of rules + initial states (not yet implemented in KaSa, but one line of code, export not difficult)
       2) take into account rhs of rules + initial states (that is what is exported by KaSa to KaSim)
       3) take into account rhs of non dead rules + initial states (implemented in KaSa, but the result is not yet included in the output).

(In mode 3), the contact map with or without lhs is the same). 

There are at least two ways for making it available.
Either you add argument to the export function , and KaSa export the requested contact map. 
Or, we compute everything but tag each piece of information so that the unrequested pieces of information can be filtered out by the server. 
(Also we can have a enlighten the impact of a given rule in the contact map effect). 

Cheers.
Jérôme.

**Comment by pirbo** [comment]
Not the case anymore+ We'll plug KaSa and its variety of outputs very soon
