### ISSUE TITLE
Be explicit about degradation in refman

### ISSUE THREAD

**Issue by pirbo** [Kappa-Dev/KaSim#315]

**Comment by jkrivine** [comment]
Salut Pierre je suis de garde de Nina aujourd'hui  (gastro)
Mais je vais essayer de me connecter à Skype sur mon smartphone

Le 7 décembre 2016 00:37:23 GMT+01:00, Pierre Boutillier <notifications@github.com> a écrit :
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Kappa-Dev/KaSim/issues/315

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by yarden** [comment]
The section of reference manual that explains this now is ``3.4.1 Pure rules -> Adding and deleting agents``. A few comments:

1. The section doesn't describe the simplest operation which is how to delete agents regardless of their internal state, for instance:

```
'deleting_total_A' A() -> @ deg_rate
```

2. It'd be clearer if the section and the table of contents referred to "degrading" agents, since that term is typically used for degrading species in chemical reactions.

3. There are a couple of typos in the rules of the reference manual in:

```
1’deleting␣A’ A(x!1),A(z!1)} -> A(x) @ ’gamma’
```

and: 

```
1’deleting␣A’ A(x!1),A(z!1)} -> A(x) @ ’gamma’
```

(Hanging ``}`` on LHS).
