### ISSUE TITLE
make doc not working in latest commit

### ISSUE THREAD

**Issue by rhz** [Kappa-Dev/KaSim#345]
I just did a git pull from the repository and run `make doc` (after successfully compiling KaSim with `make`). I get this error:
```
! Undefined control sequence.
<argument> ...@base \Gin@ext  image\GPT@AttrShort 
                                                  \ifx \GPT@print \ltx@empty...
l.92 \tableofcontents

!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by pirbo** [comment]
The fix has nothing to do with your issue sorry. I don't reproduce though ... What latex are you using?

**Comment by rhz** [comment]
TeXLive 2016.42515 (last version available on Arch)

**Comment by vd1** [comment]
i also have a problem with make doc

> celodv:KaSim V$ make doc
> rm -rf man/generated_img
> mkdir man/generated_img
> cd man/scripts/ && KAPPABIN="/Users/V/Code/KaSim/bin/" sh abc-cflow.sh > abc-cflow.witness 2>&1 \
> 	|| { cat abc-cflow.witness; rm abc-cflow.witness; exit 2; }
> make: *** No rule to make target `man/scripts/abc-pert.witness', needed by `man/KaSim_manual.pdf'.  Stop.

**Comment by vd1** [comment]
if I run make doc a second time it goes past the first problem and then does not find pdflatex

> cd man/ && LOG=$(mktemp -t pdflatexlogXXXX); rm -f *.aux && \
> 	pdflatex -halt-on-error KaSim_manual.tex > ${LOG} 2>&1 && \
> 	bibtex KaSim_manual >> ${LOG} 2>&1 && \
> 	makeindex KaSim_manual.idx >> ${LOG} 2>&1 && \
> 	pdflatex -halt-on-error KaSim_manual.tex >> ${LOG} 2>&1 && \
> 	pdflatex -halt-on-error KaSim_manual.tex >> ${LOG} 2>&1 && \
> 	rm ${LOG} || { cat ${LOG}; rm ${LOG}; exit 2; }
> /bin/sh: pdflatex: command not found
>

**Comment by vd1** [comment]
OK so i added pdflatex to my paths and it works

**Comment by vd1** [comment]
there is a typo in the manual on page 28:
`2 %init: ’n’ A(),A(y\intstate p`

**Comment by pirbo** [comment]
@vd1 your problem is solved but @rhz one may remain...
That being said, I really cannot reproduce @rhz (I did not go until installing arch in a vm but I did install the very last texlive from texlive directly and `make doc` is working fine). `make clean` was not exhaustive with respect to files generated by `make doc`. Can you update, clean (if you did not put any of your file in the KaSim directory, you could even try to `git clean -dxf`. Check with `git clean -dxn` before using this nuclear weapon) and retry to build?

**Comment by rhz** [comment]
OK, after `git pull`, `make clean`, `git clean -dxf`, `make doc` I still have the same problem. The problem seems to be caused by the includegraphics commands that have the option `natwidth` and `natheight`. After commenting out all of them, it compiles but the pdf doesn't contain those images of course (the other images are fine).

**Comment by pirbo** [comment]
Thank you very much for digging out the source of the problem.
It helps me realise that even if my debian/MacOS pdflatex TexLive2à&6 is not crashing, the outputted pdf does NOT contains the graphics where a `natheight` has been used. You can see why [here](http://tex.stackexchange.com/questions/234577/undefined-error-when-trying-to-include-eps/234747#234747).
I did not realise that earlier because the continuous integration tool that publish the compiled RefMan each commit uses an older texlive.
However, these `nat{height, width}` have a purpose. They have been introduced because the html backend (`htlatex`) is not able to resize graphics without them (even TexLive2016 version). So we are stuck! Conclusion, we need to find an alternative to `natheight`for `htlatex` but I have no time now...

**Comment by rhz** [comment]
So you generate the html directly with TeXLive? Using pdf(la)tex? Are there preprocessor macros to say "when compiling this as html do this, otherwise do that"?

**Comment by pirbo** [comment]
The command used (in the `man` directory of the repo) is 
```
htlatex KaSim_manual.tex  "nma.cfg,htm,charset=utf-8,p-width" " -cunihtf -utf8" "" "-halt-on-error"
```

**Comment by rhz** [comment]
OK, then maybe we do the following:
```
cp KaSim_manual.tex KaSim_manual.htlatex
sed 's/,natwidth=[0-9]*pt,natheight=[0-9]*pt//' KaSim_manual.htlatex > KaSim_manual.tex
```
Then use
```
htlatex KaSim_manual.htlatex  "nma.cfg,htm,charset=utf-8,p-width" " -cunihtf -utf8" "" "-halt-on-error"
```
to generate the html?

After removing all the `natwidth` and `natheight` with `sed` the pdf compiles in my computer. There seems to be a blank page at the end of some chapters but maybe this is intended?

**Comment by pirbo** [comment]
@rhz Can you check that it indeed fix the issue for you?

**Comment by rhz** [comment]
I'm afraid it doesn't
```
Package pdftex.def Warning: Option `bb' does not make sense,
(pdftex.def)                using `viewport' instead on input line 95.

<use img/KaSim-Logo.pdf> [6]
Chapter 1.
<use img/KaSim-Logo.pdf>
! Undefined control sequence.
<argument> ...@base \Gin@ext  image\GPT@AttrShort 
                                                  \ifx \GPT@print \ltx@empty...
l.96 ...atwidth=375pt,natheight=200pt]{\KaSimLogo}
                                                  \end{center}
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by pirbo** [comment]
Sorry There were a remaining natwidth...

**Comment by rhz** [comment]
Cool! Now it's working :)
