### ISSUE TITLE
Typing enter in the perturbation window should execute perturbation

### ISSUE THREAD

**Issue by majorseitan** [Kappa-Dev/KaSim#357]
When the user types enter in the perturbation window it should
execute the perturbation.

**Comment by hmedina** [comment]
I ran a model until T>10. It paused. I then entered 20, and hit enter. Grave mistake...

If I hit enter on the PauseIf box, the whole screen goes dark gray. I can't scroll (though I can arrow around), so I can't dismiss the "invalid perturbation" dialog I assume popped up somewhere; I'm effectively "locked" out. My simulations (plural!) keep running in the background, forever lost to me... any changes in my code are now consigned to digital oblivion...

I'm changing this to a critical bug because hitting Enter on a parameter box (which is standard behavior) has caused code & simulation loss.

**Comment by pirbo** [comment]
AHAH by complete change, my maniac rewriting of the fix fixed your issue @hmedina ! This is BAD, this encourage me to be maniac ...
