### ISSUE TITLE
Hierarchy of tabs in workspace

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#367]
Right now, the hierarchy of tabs in the workspace is:
Project > Editor/Plots/Fluxes > Files/Simulations

Wouldn't it make more sense to have:
Project > Files/Simulations > Editor/Plots/Fluxes

A project has kappa executable code (i.e. files) and it's results (i.e. simulations). Those in turn can have outputs (e.g. plot, snapshots, maps). This would be using a "has" metaphor for the hierarchy.

**Comment by pirbo** [comment]
I agree with you but I would be more radical: I'm more and more convinced each day that there should not be several simulation per projects. We may provide at the UI level  a button "clone project" instead (which is impossible as long as #361 is there).

**Comment by hmedina** [comment]
I think multiple simulations per project make sense and can be a good tool if there is sharing of the initialization step between simulations. Here is my train of thought:

A project has a single kappa executable code (spread in however many files you want). Coupled with a random seed, it can yield traces & simulations. Assuming that the initalization ("domain construction" I believe it's called?) is independent of the seed, a single project could generate one intialization step, share it across simulations, and yield multiple traces/executions, no?

**Comment by pirbo** [comment]
In any know model, building the initial mixture is longer than all other initialisation steps combined. (We might have to work on that 1 day). Simulation mixture is modified "in place" so 1 initial mixture cannot be used for several simulations.
That's why I think building up the machinery for sharing initialisation is oversized for now. (even if now that I think about it copying a mixture might be cheaper than building it :-))

**Comment by feret** [comment]
Yes, it would be worth trying a physical copy, if this is not to much memory intensive.

Cheers. 
Jérôme.

**Comment by pirbo** [comment]
The current API has only 1 simulation per project.
