### ISSUE TITLE
Kappa hangs on initialization step

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#389]
Hello,

I have the following Kappa model:

```
%agent: S(x,y) 
%agent: A(x)
%agent: B(y)

# S binds A
'R1' S(x),A(x) -> S(x!1),A(x!1) @ k1
# When S and A are bound via x, B binds A via y
'R2' S(x!1,y),A(x!1),B(y) -> S(x!1,y!2),A(x!1),B(y!2) @ k2

%var: 'k1' 1.0E-2
%var: 'k2' 1.0E-3
%var: 'S_amount' 20
%var: 'A_amount' 20
%var: 'B_amount' 20

%obs: 'S' |S()|
%obs: 'A' |A()|
%obs: 'B' |B()|

%init: 'S_amount' S()
%init: 'A_amount' A()
%init: 'B_amount' B()

%mod: [T]=50 do $ADD 50 A()
%mod: [T]=60 do $ADD 50 B()
%mod: [T]=100 do $DEL inf B()
```

The last perturbation (which is intended to delete every copy of agent ``B``) makes this model hang. When I run it with KaSim, I get:

```
$ KaSim test.ka
+ Self seeding...
+ Command line to rerun is: 'KaSim' 'test.ka' -seed 1064239883
Parsing test.ka...
done
+ Sanity checks
+ Compiling...
+ Building initial simulation conditions...
	 -simulation parameters
	 -variable declarations
	 -rules
	 -perturbations
	 -observables
	 -update_domain construction
	 10 (sub)observables 2 navigation steps
	 -initial conditions
File './data.csv' already exists do you want to erase (y/N)?
y
+ Building initial state
Done
0.05 time units in 1 events
```

and it hangs indefinitely. If I use the Kappa app for Mac OS X (thanks to @pirbo for making nightly build available) then it also hangs with "Initializing" status and there doesn't seem to be a way to interrupt it:

![kappa_hanging](https://cloud.githubusercontent.com/assets/96318/25234322/bce72582-25af-11e7-894b-305bca43bfeb.png)

(Is there a way to interrupt/restart simulation in the app?)

If I comment out the ``$DEL`` perturbation, it works. 

Thanks for your help.

**Comment by pirbo** [comment]
It does not hang during initialisation.
It hangs removing an infinity of B at t=100. You don't see that because progress report are not updated because of the infinite loop...
I understand that you mean `%mod: [T]=100 do $DEL |B()| B()` by `%mod: [T]=100 do $DEL inf B()` and silently looping is clearly a bug. (It is not completely silent internally, it generates warnings but because there are not flushed, result for users is the same !) 
I'm not sure what should be the fix. When KaSim cannot apply a perturbation, it should:
0/ emit a warning and continue to try to apply the perturbation (current situation, clearly not satisfactory)
1/ emit a warning, stop applying the perturbation but continue the simulation
2/ emit an error and stop the simulation

**Comment by yarden** [comment]
I was following the [reference](http://dev.executableknowledge.org/docs/KaSim-manual-master/KaSim_manual.htm) manual that says: *"Also the perturbation eﬀect: $DEL inf B(x!_) will remove all Bs connected to some agent from the mixture"* So it sounds like the correct way to do this is ``%mod: [T]=100 do $DEL |B()| B()`` (on separate note, the KaSim app cuts off the simulation at the time of the last perturbation and doesn't seem to take into account the "Pause if" ``[T] > x`` conditions, which I think is a bug - previous versions did it correctly).

Regarding perturbations that cannot be applied, your proposal 1 makes most sense to me. Regardless of how this is handled, for KaSim app, it'd be great to have a way to interrupt the simulation even if it's not in an infinite loop. Right now if you have a simulation that takes a while or that has an infinite loop, there's no way to change it apart from restart KaSim App.

**Comment by pirbo** [comment]
I've fixed the manual (thanks) I've implemented 2 after discussion in the lab.
>  the KaSim app cuts off the simulation at the time of the last perturbation
No, after the last perturbation, the activity of the system is 0, no rule applies. The simulator therefore deadlocks. It is not clear in the app because you have to go in subtab "log" of tab "editor" to see the error message (the fact that a snapshot `deadlock.ka` is generated can serve as an insight too) This is #331.
I don't understand your last remark, simulation that take a while are interruptible (Ctrl-C in the command line, "pause" in the app) ...

**Comment by yarden** [comment]
Thanks for clarifying the deadlock issue. Simulation is of course interruptible from command line, that's no problem, but in the webapp itself, I don't see a "Pause" button (see my screenshot). When it gets into infinite loop, it displays "Initializing" and there's no simulation control button that I can see.

**Comment by pirbo** [comment]
I see, an initialisation that take a while "for good reason" is not interruptible. Good remark
