### ISSUE TITLE
Rules written in edit notation always use new syntax for free site (and it is confusing)

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#396]
The statement from the manual:
```'Disconnect␣A' A(x!_/) @ ’gamma’ ```
Gets flagged as an error by the UI, with:
```1/1[foo.ka] Incorrect link modification ```
![capture](https://cloud.githubusercontent.com/assets/1588553/26031664/eb1fcf24-3849-11e7-9a3f-1c9350a1b20b.PNG)

Meanwhile, WebSim says:
```WebSim: main: [{"message_severity":"error","message_text":"Incorrect link modification","message_range":{"file":"foo.ka","from_pos":{"line":3,"chr":22},"to_pos":{"line":3,"chr":24}}}]```

Even when correcting the agent signature so that it holds an site named `x`, the error is the same.

On the note of notation, I was under the impression we would be adopting a notation of the like `[new-state]`; e.g. `~[a]` put in state `a`, `![1]` put in bond `1`, `![]` for unbind, etc.

**Comment by pirbo** [comment]
2 changes have been made to the syntax:
- an edit rule notation has been introduced. This is a safe extension.
- The notation for "a site is free" has changed. This is problematic because it walks on the foot of the old notation. Concretely `A(x)` becomes `A(x!.)` and `A(x?)` becomes `A(x)`. That is more in line with the "don't care don't write" principle (because you don't have anymore to write an extra `?` to test less) but it has the huge drawback that `A(x)` is correct in both syntax but has a different meaning!!!

Now, we are in the middle of the bridge:
- rules in chemical notation are written with the old convention for free sites
- rules in edit notation are written with the new syntax for free (The rule you want to write is spelled: `'Disconnect␣A' A(x!_/!.) @ ’gamma’`, the one you wrote is `A(x!_) -> A(x?)` in chemical notation and therefore is ambiguous)
- patterns in algebraic expression are in old free convention by default but there is an option `%def: "newSyntax" "true"` to activate the new convention.

This is not a satisfactory state. Yes. I must come back to that but I'm super bored of being the only one  trying to reach a consensus surrounded by people fighting for there own preference.
As a consequence I won't implement the squared syntax for modification, myself. The thing I'll do is that if @jonathanlaurent, who fights for it, comes with a coherent patch that deal with all cases and take into account backward compatibility. I'll accept it :-)

**Comment by hmedina** [comment]
Sorry, wrong button mis-closed the issue.

**Comment by pirbo** [comment]
This is the continuity of #204
