### ISSUE TITLE
KaSa is not working anymore in the GUI

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#416]
I get the error:

1/1 {"caught":[],"uncaught":[{"file_name":"KaSa_rep/data_structures/mvbdu/mvbdu_wrapper.ml","message":"line 278: MVBDU should be initialised once only"}],"calling_stack":[]}

**Comment by feret** [comment]
KaSa errors are not blocking. 
Maybe we should show the errors but also the result of the computation

**Comment by feret** [comment]
I have changed the behaviour of Remanent_state.create_state so that it may be called several times. 
At the first call, memoization tables are created
At further calls, memoization tables are preserved (so that bdus maintain what they have learned); except it the optional argument 'reset'  is set to true, in such a case, they are reinitialised.

**Comment by feret** [comment]
@pirbo, I let you check that I did nothing to wrong.

**Comment by feret** [comment]
No news. no worry. I close the issue.

**Comment by pirbo** [comment]
Sorry, yes your changes are perfectly fine.
I started to change the API so that you can get successes and errors at the same time, then I drawn, then I've been interrupted, than I forgot... It is a rather deep change of the "logic" of the protocol so it requires more thoughts.

**Comment by feret** [comment]
Great thanks!
I like better late but efficient answers, than quick but useless ones.
