### ISSUE TITLE
Potential bug in KaDE conversion of Kappa programs to ODEs as SBML

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KaSim#449]
Hello,

I've run into a potential bug with KaDE's conversion of Kappa programs to ODEs. When I convert this [Kappa program](https://gist.github.com/yarden/a0a06b9f4bfd3a1d154f945f455d0837) to ODEs in SBML format using KaDE, I get this [XML file](https://gist.github.com/yarden/a918d52c846f810b2c2fa2887b297dce).

It seems like several agents and rules that are in the Kappa program are missing from the XML file. For instance, the agent ``Gal(gal_ext)`` doesn't seem to have any corresponding species in the SBML file. The agent name ``Gal(gal_ext)`` doesn't appear at all in the ``name=`` attribute of species declarations in the SBML file (while ``Glu(glu_ext)``, which has a nearly symmetric role in the Kappa program to ``Gal(gal_ext)``, does appear in the SBML file). So it seems like the program is only partially converted to ODEs? Any clarification on what might be happening would be greatly appreciated.

Thanks very much. Best, Yarden

**Comment by pirbo** [comment]
Hi Yarden,
The ODE generator starts from the set of the species present in the initial condition, it computes the set of the species reachable from this initial set by a rule application, it computes the set of the species reachable from this second set by a rule application, ... until it reaches a fix point.

It looks like there is no way to generate a `Gal()` from the initial condition you provide so it is not the SBML file...

This is reconfirmed by putting your model in the UI and either asking for the (High resolution contact map which is the cryptic name for the contact map of reachable agent in which you don't see `Gal()` or by looking at the dead rules tab where all the rules that involve a `Gal()` appears...

**Comment by yarden** [comment]
Hi Pierre,

I see. That way of generating ODEs breaks my pipeline, though, and any advice on how to get around it would be appreciated. I'll explain my use case more: Since the input to my Kappa program is a complex (and random) set of perturbations, the initial conditions are not very interesting. That is, given the initial conditions stated in Kappa you indeed cannot generate a ``Gal()`` agent, but with the perturbations I feed the Kappa program you can and will generate ``Gal()`` agents. I was hoping to maintain a separation between the logic of the program -- i.e., the agents and the rules -- and the set of perturbations that can be fed to the program. My goal is to generate a set of ODEs that correspond to the Kappa program's logic, i.e. its rules, and then run these ODEs on a set of inputs corresponding to my perturbations to compare the deterministic and stochastic behaviors. 

However, I can appreciate that pruning out the agents not reachable from the initial states makes the automatic conversion from Kappa to ODEs more tractable. Is there a way to turn that off, though, and ask KaDE to generate an ODE for all species, even those not reachable from initial conditions?

Thanks very much.

**Comment by hmedina** [comment]
Hi all,

It sounds to me like the inputs.ka file might have what Yarden needs to get
the ODE system he wants, at least for now.

Yarden, if I understand your workflow, you have a ruleset (i.e. logic) and
on a separate file/source you have parameters. If you ask for the ODEs of
just the logic, it is missing stuff because they are unreachable. However,
after you determine parameters, feed them to KaSim, and execute the model,
you will generate an inputs.ka file with the logic and every perturbation
to it. For example, if you add gal() at some point, the inputs.ka file will
have that as a perturbation (provided you simulated up to the perturbation
time). Thus the gal() species become reachable. I believe this file should
then be able to generate the ODE system you expect.


Best
Hector

**Comment by pirbo** [comment]
Maybe/probably not :-)

You've got a good intuition @hmedina . There is a ugly hack in KaSim if you want to say to the system that a species is reachable even if nothing allows to get it from the initial condition: writing a non realisable perturbation that add it like for example:
```
%mod: [false] do $ADD 1 Gal()
```
(I know... I know... Sorry :-D)
BUT
KaDE does not deal with perturbations at all!
So, it will (probably) ignore that `Gal()` can be (realisably or not ;-)) added later... (I'm not 100% sure and I really don't have the time to check today therefore I did not replied earlier) The only tricks I can think about for now is to add some artificial
```
%init 1 Gal()
```
and then to edit the SBML file obtained is necessary.

If @feret doesn't come with a answer before, I'll dig into that (and the other relevant issues raised by @yarden) more seriously next Wednesday

**Comment by feret** [comment]
Dear Yarden, 

This is not possible to generate an ODE that will work for all the perturbations that you may have in mind without providing an explicit superset of the perturbations (or an explicit superset of the species that they may introduce). 

Let us imagine that I have an agent A(x,y). 
Then, we may consider the perturbation introducing a chain of n As. 
As long as we have an agent with two sites, we may introduce infinitely many different species by the means of perturbations. 

There are several solutions both based on a superset of the species that you may introduce. 
(the first one required some further implementations in KaDe; the second one is already working). 

-> If you give a superset of perturbations, then it is enough to scan the perturbation and take into account potential introduction, but this is not implemented yet. 

I am a bit reluctant to do this, because this would be only a partial treatment of perturbations. 
Former tools had a less expressive perturbation languages that was fully covered by the ODE generator. But here, I would need more works. 
I would prefer to implement full support for perturbations, rather that just taking into account the species that may be potentially created by perturbations, and not the discrete/hybrid effect of the perturbations. 

-> You collect the set of species that you may introduce by perturbations, and you introduce them at 0 concentration. 

In KaDe, models are completely parametric. 
When you use %var: 'k' 1 
There is a line in the model where you can  modify the value of k, and the ODE is still valid.
The ODE is completely parametric.  

This is the same for the value 0. 
When I write %Init: 0 Gal(), my ODE is still valid if I replace 0 by any value. 
Thus KaDe has to provide you the equations related to Gal. 
Even if the concentration of Gal remains equal to 0, unless you perturbation the model. 

Does it answer to your question? 
Are you OK with the second solution? 

Best regards.
Jérôme.

*****************************************************
Please note that KaSa computes the set of reachable states and the set of reachable agents. 
It takes into account agent introduced with a null concentration, as well as the agent potentially introduced with perturbation.

**Comment by pirbo** [comment]
Ok then the KaDE compatible version of
```
%mod: [false] do $ADD 1 Gal()
```
is
```
%init: 0 Gal()
```
Right?

**Comment by feret** [comment]
Yes.  You are completely right Pirbo. 


If there is a demand, I can update KaDe so that it only consider Gal to be reachable if used in the following perturbation: 
%mod: [false] do $ADD 1 Gal()

Indeed KaSa understands both. 

Just let me know. 
But it is not urgent, and I do not have much time currently. 


Cheers. 
Jérôme.
