### ISSUE TITLE
KaSim feature request: --dumpFinalState finalSnap.ka

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#450]
It would be useful to have a command-line option to dump the final mixture as a snapshot.

In my system, observable domain construction takes upwards of an hour (observables with ~3K agents), which makes waiting in interactive mode undesirable. Outside interactive mode, I could write the snapshot as a perturbation, however I would rather not as that entails writing into the kappa program a stop/run time, which is an execution condition rather than a model element. I.e. if I change the command line arguments of `-l`, I would also have to modify the program itself in sync.

**Comment by pirbo** [comment]
We discuss with @icristescu the fact that [Tmax] and [Emax] are problematic operators (because of interactive mode but also because you can put a `$STOP` under arbitrary condition in your model. We plan to remove them (it might already be done) and to replace it with a special alarm `final` that fire only once: when the simulation has just stopped before quitting the simulator.

This is exactly what you're asking for and there is no technical barrier I can think about.

The question is (as raised by #445) that even if this alarm ecology is clean from the language designer end, it might not follow the intuition of users and therefore might not be the best choice...

**Comment by hmedina** [comment]
So `$KaSim -i model.ka --final finalSnap.ka -l 5 -u time` would be valid? That syntax makes sense to me. Would it fire once everything has finished yet before the very first event after `T > 5.0f` ? I.e. it fires /after/ the the mix gets modified by the last event before `T > 5.0f` and all the perturbations have triggered?

**Comment by pirbo** [comment]
I would rather go for a perturbation in the kappa file than a command line option but we may discuss the need to make `--final finalSnap.ka` an alias for (unfixed syntax):
```
%mod: alarm finally [true] do $SNAPSHOT finalSnap.ka repeat [false]
```

Yes, it fires __after__ the the mix gets modified by the last event before T > 5.0 and all the perturbations have triggered if you don't Ctrl-c the simulation and the kappa file contains no `$STOP` modification.
It fires after the $STOP modification if there is one somewhere

**Comment by jkrivine** [comment]
Hi

But what do you mean by final mixture? Is it deadlocked or do you have a 
stopping time condition?

**Comment by hmedina** [comment]
Hi Jean,
In this case, I specify a run-time in the command line. As such, the model has not `$STOP` perturbation. Thus the final mixture is the very last state the mixture existed before the program terminated. The use-case is clearer when you consider the `--continue` option:

I run a model, don't know if it has reached interesting behavior, so I store the final state:
``$KaSim -i m.ka --final-mix foo.ka -l 5``

It didn't reach interesting behavior, so I continue from where I left off:
``$KaSim -i m.ka --continue foo.ka -l 5``

**Comment by pirbo** [comment]
I met with myself and I decided that I won't implement anything for KaSim 4.0 as there is a workaround that I find sufficient (but please complain if you don't):

Instead of writing `KaSim --final finalSnap.ka -l 5 m.ka` on the command line. Add
```
%mod: [T] > 'time_limit' do $STOP "finalSnap.ka"
```
in `m.ka` and launch it by `KaSim -var time_limit 5 m.ka`

**Comment by hmedina** [comment]
That covers the use case, so works for me.
