### ISSUE TITLE
"Try it online" button points to a wrong url

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#479]
It's in the title!
:)

**Comment by pirbo** [comment]
kappalanguage.org is in huge trouble thanks to LetChangeAbsolutlyEverything5MinutsBeforeChrismasBreak©

https is not working, some URL gives 403 errors ... We have now to wait for Havard network and web teams return in order to get something decent!

In the meantime, api.executableknowledge.org is still up and is now corrected for what it's worth...
