### ISSUE TITLE
Wrong or unclear error messages

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#481]
forgetting a parenthesis in the expression:
%obs: 'ab complex' |A(x[_]| 
produces the error:
--> 1/1[model.ka] invalid linking state or missing ']'
that should mention the missing ')' and not ']'

Putting in the perturbation tab
$ADD 100 A()
produces:
--> problematic effect list 
error. From the manual it is not clear I am doing anything wrong and the error message is rather unhelpful.

**Comment by pirbo** [comment]
> Le 4 janv. 2018 à 10:49, Krivine <notifications@github.com> a écrit :
> 
> forgetting a parenthesis in the expression:
> %obs: 'ab complex' |A(x[_]|
> produces the error:
> --> 1/1[model.ka] invalid linking state or missing ']'
> that should mention the missing ')' and not ']'
This one is obvious and I can probably do something for it
> 
> Putting in the perturbation tab
> $ADD 100 A()
> produces:
> --> problematic effect list
> error. From the manual it is not clear I am doing anything wrong and the error message is rather unhelpful.
The problem here is "Every effect list must now end with a semi colon"
I know a lot of people including me will super often forget the final `;` but I don't manage to find a way to make a relevant error message (In a way, if I did, the terminating `;` would have not be mandatory as I would have find a way to detect the end of an effect list without requiring a `;` and I would have not required it :-) )

**Comment by hmedina** [comment]
I've seen platforms suggest stuff when it's difficult or unclear what the real error might be. For example, one could change the current error message to:
```
--> problematic effect list. Forgot ending semicolon?
```
