### ISSUE TITLE
Perturbation syntax in manual is incomplete

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#487]
The syntax described in the manual under 2.7.1 is missing the parenthesis around the effect list.
KaSim offers very cryptic error messages without those (undocumented) parenthesis.

**Comment by pirbo** [comment]
> KaSim offers very cryptic error messages without those (undocumented) parenthesis.

Probably, you forgot the mandatory terminating `;` at the end of the effect list

The fact that you can put parentheses around effect list (and that in that case you can omit the final `;`) is not documented because formal grammar is a bit ugly there (you can put effects before the parentheses but not after...) so it need to be fixed before being publicly exposed !

**Comment by pirbo** [comment]
There is nt this problem anymore in the new manual
