### ISSUE TITLE
Intervention, the example in the handbook seems not to work. 

### ISSUE THREAD

**Issue by feret** [Kappa-Dev/KaSim#515]
I tried the following intervention: 

%mod: alarm 2.3 [true] do $PLOTENTRY; repeat [true]

The intervention seems to be triggered only twice, at time t=0 and at time t=2.3. 

The same for the following one: 

%mod: alarm 1 [true] do $ADD 1000 A() ;  repeat [true]

(at time t=0 and at time t=1).

**Comment by hmedina** [comment]
The semicolon marks the end of a modification line. The default value for
repeat is false. Thus this line reads as two commands, where the second has
no effect:

%mod: alarm 2.3 [true] do $PLOTENTRY repeat [false]

repeat [true]

I have encountered this behavior several times, and it is never what I
intended. In addition to fixing the  documentation, may I propose throwing
a syntax error when a command containing exclusively 'repeat [true]' is
found?

On Mar 12, 2018 05:28, "Jérôme Feret" <notifications@github.com> wrote:

I tried the following intervention:

%mod: alarm 2.3 [true] do $PLOTENTRY; repeat [true]

The intervention seems to be triggered only twice, at time t=0 and at time
t=2.3.

The same for the following one:

%mod: alarm 1 [true] do $ADD 1000 A() ; repeat [true]

(at time t=0 and at time t=1).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kappa-Dev/KaSim/issues/515>, or mute the thread

**Comment by feret** [comment]
Thank you Hector. 

Could you give me the syntax to add a fix amount of a given protein at a fixed period of time ? 
When I remove the semicolon, I get an error: 

%mod: alarm 1 [true] do $ADD 1000 A() repeat [true]

-> Malformed site expression

**Comment by pirbo** [comment]
No, no, it's an obvious bug! What you're doing is what is supposed to be done.
We are in floating point arithmetic hell... Something should be equal to 0. in order for the perturbation to fire but errors accumulate and it end up being equal to ~1e-16....
I've not pushed an hot fix because I don't want to add tapes on tapes on tapes. Logic to fire perturbation is already too messy in my opinion. It requires a well fought cleanup more than an in a hurry workaround.

**Comment by hmedina** [comment]
Oh really @pirbo ...? Hackerman to the rescue!

```
%agent: A(a)
%init: 10 A(a)
A(a[.]),A(a[.]) <-> A(a[1]),A(a[1]) @ 1,1
%mod: alarm 1 [true] do ($ADD 1 A();) repeat [true]

%obs: 'A' |A()|
%mod: [T] > 10 do $STOP;
```
@feret just put parenthesis around the effect(s) ;)
![itjustworks](https://user-images.githubusercontent.com/1588553/37314051-60a49406-2628-11e8-978b-c82a200449e7.png)

**Comment by feret** [comment]
Hector, 

You code works with and without the parentheses. 

Indeed the issue does not come from the parenthesis. 
It occurs only with models without rules. 

Adding a spurious rule to my model, makes the intervention works properly. 

Thank you for your help.

**Comment by pirbo** [comment]
That was ugly...
Evidences of huge bugs were there in front of our nose in the test-suite but we didn't even noticed!
I hope it's better now.

**Comment by feret** [comment]
@pirbo, you're the best. 
It is working perfectly now.
