### ISSUE TITLE
Installation options are incomplete

### ISSUE THREAD

**Issue by glucksfall** [Kappa-Dev/KaSim#516]
Hello everyone,

I found a hard time installing KaSim from the master branch because I'm using Ubuntu 17.10

First, I needed to change the compiler version with `opam switch 4.02.3` The lastest system compiler version 4.04.0 make this error while trying to install KaSim

```
File "myocamlbuild.ml", line 1:
Error: Files /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa
       and /usr/lib/ocaml/unix.cmxa
       make inconsistent assumptions over implementation Unix
```

Ok, that was fixed changing the ocaml compiler to a previous version. Now, `make all` complained because the package lwt wasn't installed and that is it not present in the README.md installation section (only yojson).

Thank you for your time,

Best regards

**Comment by hmedina** [comment]
Hi Rodrigo,
Yes, installation instructions have not been updated in a while. If it helps, my process to get KaSim & WebSim running under the Windows Sybsystem for Linux, Ubuntu flavor, is the following:


1. Get & install WSL
	1. Look up package "Ubuntu" in the Microsoft Store, follow directions
	1. Update ubuntu's package list & sources
		1. `$ sudo apt-get update; sudo apt-get upgrade`
1. Install OPAM dependencies with
	1. `$ sudo apt install gcc unzip m4 make git aspcud`
1. Install OPAM
	1. https://opam.ocaml.org/doc/Install.html
		1. `$ wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin`
	1. Run `opam init`; option 'f' for file: make sure it updates ~/.bashrc instead of ~/.profile (http://askubuntu.com/questions/835560/why-does-my-custom-prompt-not-show-in-ubuntu-bash-on-windows-10)
	1. Make sure the right version got installed: `opam switch` displays installed and current environments, install a new one via:
		1. `$ opam switch 4.05.0`
1. Use Opam to install dependencies:
	1. KaSim's
		1. `$ opam install ocamlbuild ocamlfind yojson`
	1. WebSim's
		1. `$ opam install atdgen cohttp-lwt-unix`
1. Use Opam to install the dev "branch" of KaSim (otherwise it would fixate on the stable releases)
	1. `$ opam pin --dev add KaSim`
1. To use WebSim:
	1. Launch the websim server (opam added it to path):
		1. `$ WebSim`
	1. Point browser to the right port http://dev.executableknowledge.org/try/index.html?&host=http://localhost:8080/

**Comment by pirbo** [comment]
First part (`inconsistent assumptions over implementation Unix`) is not Kappa fault.
If OCaml and ocamlbuild were both installed by apt, there might even be a bug in ubuntu... (although I'm surprised because if you have a installed and set up opam as you claim then opam should install and use its own ocamlbuild and not use the system one (in `/usr/lib/..`) ...) Anyway, Something is fishy but it is not our busyness ;-)

Other remarks are relevant for us and I tried to refresh README.md accordingly. Do you think it is clearer and more accurate now?

**Comment by glucksfall** [comment]
Hi @hmedina @pirbo 

Thank you all. Yes, I think now is clearer and complete. I wrote the issue because I'm working on a software that relies on KaSim (and others stochastic engines) to simulate and now I'm updating the code to be compatible with the latest releases (Also the steps to install those engines in Ubuntu in the paper supplementary material). I compile KaSim from the Github master branch doing `make clean && make all`. I haven't done that in a while because I found that bug in OCaml and I knew it wasn't your busyness. Surprisingly, the version 4.04.0 is buggy (both the so-called system compiler and the local when using `opam switch 4.04.0`) and I think for now "OCaml native compiler version 4.02.3 or above" in the README.md you should stick to the first. At least for new users risk-loving like my installing a non LTS Ubuntu.

Best to all, thanks for your time
