### ISSUE TITLE
Current release to PyPI can not install

### ISSUE THREAD

**Issue by cthoyt** [Kappa-Dev/KaSim#518]
I didn't have this problem when intalling on mac, but when I'm installing from Linux [Scientific Linux release 7.3 (Nitrogen) 3.10.0-693.2.2.el7.x86_64] it looks like there's a problem with the README file

```bash
[1034] [10:14] [choyt@lisa:~/dev/]
$ python3 -m pip install kappy
Collecting kappy
  Using cached kappy-4.0.0.dev4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-otqku_u5/kappy/setup.py", line 51, in <module>
        long_description=readme(),
      File "/tmp/pip-build-otqku_u5/kappy/setup.py", line 44, in readme
        with open('python/README.rst') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'python/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-otqku_u5/kappy/
```

**Comment by pirbo** [comment]
I don't know how to solve this correctly. When pip does not find a binary version for a given configuration, it silently chooses to try to install an older version... (here `kappy-4.0.0.dev4` which was indeed completely broken instead of `4.0.0-rc1` which should be OK)
We provide kappy for linux only for python 2.7, 3.5 and 3.6. Could it be the issue here? (if so, I'll try to build a wheel that fit your needs)

(In fact, we don't care about python version as our binaries are python version independent. This is a limit of the wheel system that is made to make C extension of the python runtime and not what we use it for (shipping independent binaries). So, you could very well rename` kappy-4.0.0rc1-cp36-cp36m-manylinux1_x86_64.whl` into `kappy-4.0.0rc1-cp34-cp34m-manylinux1_x86_64.whl` and you would have a 3.4 version :-))

**Comment by cthoyt** [comment]
Aha! We are indeed on Python3.4. I'm not so personally happy with this, but it is an organizational thing. Maybe this is a good excuse to convince IT to upgrade us :)

Thanks so much for the help
