### ISSUE TITLE
Weird result for influence map

### ISSUE THREAD

**Issue by bgyori** [Kappa-Dev/KaSim#561]
In the following model, TP53 can be in an inactive and active state. There is a single rule in which inactive TP53 is produced. However, the influence map shows the observables for both active and inactive TP53 as positively influenced by this rule:
```
%agent: TP53(activity{inactive active})
%agent: MYC()

%var: 'kf' 2e-04
%var: 'TP53_0' 10
%var: 'MYC_0' 10

'MYC_produces_inactive_TP53' MYC(),. -> MYC(),TP53(activity{inactive}[.]) @ 'kf'

%obs: 'TP53_active' |TP53(activity{active}[.])|
%obs: 'TP53_inactive' |TP53(activity{inactive}[.])|

%init: 'TP53_0' TP53(activity{inactive}[.])
%init: 'MYC_0' MYC()
```
Attached the image from https://tools.kappalanguage.org/try:
![im](https://user-images.githubusercontent.com/5939016/54962514-8edca380-4f3b-11e9-9ff5-56ce3fb0d6c0.png)

Isn't it the case that the rule should have no influence on active TP53? Sorry if I'm confused!

**Comment by feret** [comment]
Dear Ben, 

You should tune the accuracy of the abstraction. 

There are three levels of accuracy. 

At low resolution, an influence is reported whenever a rule modifies at least one bit of information towards the application of another one (Manhattan distance). Here the influence is reported because the rule creates an instance of TP53. This is an artifact of the abstraction.

At medium resolution, the engine discards the low res influences that are not possible from a syntactic point of view. Here TP53 is created inactive whereas TP53_active requires it to be active, thus this fictitious influence is removed. 

At high resolution, the engine also takes the semantics into account, it checks that patterns may occur in a reachable complex. For instance if a site is phosphorylated whenever it is bound. Then a rule that unphosphorylayte the site cannot influence positively a rule that requires the site to be bound. 

Cheers. 
Jérôme.

**Comment by bgyori** [comment]
Thanks a lot for the explanation @feret, that resolves it!
