### ISSUE TITLE
Comment nesting in GUI

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#567]
The following code is interpreted correctly by the simulator, but not properly highlighted by the GUI. Specifically, `close1 */` is not parsed as comment. Is there a setting to tell CodeMirror that multi-line comments can be nested?
```
/* open1 /*open2 close2*/
close1 */
%agent: A()
A()+ @ 1
```

![Capture](https://user-images.githubusercontent.com/1588553/56389835-96206580-61f8-11e9-8439-12ada5d813a3.PNG)

**Comment by pirbo** [comment]
@yvan-sraka I thought we solved that...
Can you have a look?

**Comment by yvan-sraka** [comment]
Yes, I can reproduce the issue in the online Kappa simulator (https://tools.kappalanguage.org/try/)!

This would say that we miss something in this [commit](https://github.com/Kappa-Dev/KaSim/commit/bc495e593f332a7ca724ef2af059983cca6169e8) ...

I also checked (just to be sure) that we have the right version of `Kappa.js` online: 
- https://github.com/Kappa-Dev/KaSim/blob/master/viz/Kappa.js
- https://tools.kappalanguage.org/try/Kappa.js?7173

**Comment by yvan-sraka** [comment]
Okay so updated `Kappa.js` in PR https://github.com/Kappa-Dev/KaSim/pull/569, the issue is fixed if we agreed on this comportment (which is the one implemented in Kappa) :

- `//` have precedence on `/*` and `*/`, so everything in a line after `//` is ignored
- `/*` and `*/` could be nested, like `(*` and `*)` in OCaml

**Comment by pirbo** [comment]
Yes, I agree
Thank you very much!
