### ISSUE TITLE
Problematic error location

### ISSUE THREAD

**Issue by jkrivine** [Kappa-Dev/KaSim#579]
The following rules produce a badly located error message
/* Rules */
'a.b' A(x[.]),B(x[.]) -> A(x[1]),B(x[1]) @ 'on_rate'
'a..b' A(x[1/]),B(x[1/.]) @ 'off_rate' //AB dissociation

The error being in the second line 1/ should be 1/.

**Comment by hmedina** [comment]
With one blank line:
![Capture](https://user-images.githubusercontent.com/1588553/57551712-ba72ec00-7337-11e9-89e7-7226562c5d1a.PNG)

With _two_ blank lines:
![Capture](https://user-images.githubusercontent.com/1588553/57551737-cfe81600-7337-11e9-8a53-e2cbc7144fc0.PNG)

Seems like the GUI _really_ wants to mark line 3, regardless of where the issue is...
