### ISSUE TITLE
Show all digits for float numbers (eg time) in output file

### ISSUE THREAD

**Issue by rhz** [Kappa-Dev/KaSim#76]
Hi Jean,

I'm computing Δt's (delta ts) to compute a time-weighted average of an observable. The problem is that KaSim prints only 6 digits after the decimal point by default and that causes my Δt to be zero when it's not. It would be cool if there's an option to activate something like "full presicion mode" to print all digits.

Thanks
Ricardo

**Comment by pirbo** [comment]
I now use string_of_float instead relying on Printf so floats should be printed with full precision.
BUT plotting possibilities have changed in too. You can now only give a interval in time unit between plot lines. I guess you were using here something like "print a line every event". You can still do that using `%mod: [true] do $PRINTF "data.out" <[T]." ".'var1'." ".'var2'>` (and you'll get correct precision) but it is less intuitive...

**Comment by rhz** [comment]
I think the way I was printing every event was just by running the simulator with -e N -p N. That should print every event.

**Comment by pirbo** [comment]
Yes it was ... but in KaSim 4, you can change during the simulation for how long you simulate, you can also launch a simulation without any stopping time/event and stop it later throw a signal. Therefore, specify the number of point to plot make no sens (KaSim cannot guess when to plot...) and `-p` has been replaced by `-pp plot_period` where you specify how often (in term of time unit) you want a point in the plot.
#298 is exactly about adding the possibility to specify a plot_period in term of event instead of time unit and therefore providing an easy replacement for `-e N -p N/k` (by, I don't know, for example (but it is a very bad name) `-ppe k`). I cannot find a solution that satisfy me but this issue is by chance arguing for this need :-)

**Comment by feret** [comment]
I think there are two ways to implement the I want exactly n plots. 

-> The one I would not recommend, store the plot at each event, and do the filtering after the simulations. 
==> Costly in memory, OK for time

-> The one I would recommend, is to run the simulation twice with the same seed. 
You collect the final simulation time at the first run of the simulation, and then you relaunch it with the appropriate plot_period. 
==> OK for memory, twice time cost. 
(This is already the kind of tricks we need to do statistics about the frequency of the usage of events in stories. 

Yet the second solution, does not ensure that you can plot each event, since there maybe no event between several clock ticks.
Thus perturbation could be the only way to refer to events, instead of time.

**Comment by rhz** [comment]
I like the -ppe solution. I don't see the point of asking for exactly n points (and both solutions mentioned by Jérôme sound bad to me). If you really want to have exactly n points you can ask for more points and then do a bit of post-processing. That way you don't have to run the simulation twice or have all points in memory.

By the way, as far as I remember I wanted to plot every event to debug my model.

**Comment by pirbo** [comment]
Plot every event can be achieve using `%mod: repeat [true] do $PLOTENTRY until [false]` I close the issue here, discussion continues on #298 ...
