### ISSUE TITLE
Simulation package accepts parameters

### ISSUE THREAD

**Issue by rhz** [Kappa-Dev/KaSim#77]
Hi Jean,

It would be cool if after making a simulation package I could set the value of some of the variables I have in the model (that I'm using to specify the initial number of copies of some agents) when running with -load-sim later. Right now I'm running 50x50 simulations that differ only on this and I was wondering if I could get a speed up if such a feature would be available (I'd like to run 100x100x3). What do you think?

Cheers
Ricardo

**Comment by alejob** [comment]
Hi, 
         any news about this?. I'd like to run something similar (10^6 simulations), but changing only the rates. This is to use the "iterated filtering method", that is used to adjust curves with a stochastic simulation, ie find the rates that fix my model to data.

**Comment by pirbo** [comment]
KaSim4 (the master branch) allows you (re)define algebraic variables from the command line. Allowing you to do very easily stuff like 
```for i in $(seq 15); do ; for j in $(seq 100); do ; bin/KaSim -var rateA $i -var rateB $j foo.ka -o data_$i_$j.out```
to run 1500 simulations with different values for `rateA` and `rateB`. But this is incompatible with `-load-sim`!

Making them compatible is indeed on our agenda somehow as interactive editing of kappa file is. You really need the operator "apply the minimal changes on this compiled representation of a model induced by this change" to achieve what you ask for and this is a a medium term issue...

Is the time to compile your model and getting the initial state really not negligible in front of the time of a complete run of the simulation ? Because this might more be the real issue :-)

**Comment by alejob** [comment]
Hi Pirbo,
            thanks for the quick answer. Actually, as you said, my problem is that in my simulations the initial state time is not negligible in front of the total simulation time. 

Looks great and pretty easy the way to try differents variables, but with that new option in KaSim4 are you making all the compile process/getting initial state for each new variable?, or is faster?, does it use some kind of precompiled when running different variables?

Cheers!

**Comment by pirbo** [comment]
Tmax and Emax are inlined before the generation of the simulation package.
```
$ KaSim -t 100 -make-sim toto foo.ka
$ KaSim -t 30 -load-sim toto
```
is completely wrong!
