### ISSUE TITLE
Manual is outdated & in raw tex

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#96]
The manual is in raw TeX, so users are having to compile it themselves into a readable .pdf format.

Also, there's no mention of the many wonders hidden in KaSa in the manual.

**Comment by pirbo** [comment]
Only source files have to be tracked by git. Generated files are generated and distributed at each release. So the last stable manual is available in pdf at https://github.com/Kappa-Dev/KaSim/releases/download/v3.5-190914/KaSim_manual_3_5.pdf

The end of discussion of issue #92 is exactly about documenting KaSa too. But it is in french so you have a very valid excuse for asking here :-)

**Comment by feret** [comment]
Hi Hector, 
Let me translate last message of #92. 
Coming soon. 
(Yet there are not so many wonders available at the moment in KaSa, only the contact map and the influence map).

**Comment by xl0** [comment]
Hello.
It would be awesome if the Makefile included a 'doc' target too.

**Comment by pirbo** [comment]
Sorry, not fully closed

**Comment by xl0** [comment]
Wow that was fast. Thanks!

**Comment by feret** [comment]
I think it would be interesting to have a way to recompute the figures of the manual. 
  -> I dislike when a picture in the manual is not the one I got, because it was computed with an old version of KaSim, or because the setting is not exactly the same;
  -> It can be helpful to get the script so as to understand better how to compute the image (and use KaSim) .

This would mean:
  -> move the models from models/ to man/models/
  -> include scripts to compute the images 
  -> give the repository man its own Makefile with one action to recompute the images. 
  -> and maybe a script to warn when the images change

**Comment by rhz** [comment]
Is there a permanent link to the latest version of the manual? For citations that'd be very useful. Also, I'm using the latest version of KaSim (version 4) and wanted to cite the corresponding version of the manual. Is there a link for that?

Btw, I'm having troubles running "make doc":

    (./generated_img/KaSa_options.txt
    ! Undefined control sequence.
    l.1 \\begin{verbatim}\n

Cheers

**Comment by feret** [comment]
Ricardo, 

For the second point, I have pushed a new version which should solve your problem. 
Let me know if it works for you (the previous one was working for me, thus...) 

Best wishes. 
Jerome.

**Comment by rhz** [comment]
Thanks!

**Comment by pirbo** [comment]
The development version of the reference manual is now automatically available at http://kappa-dev.github.io/docs/KaSim-manual-master/KaSim_manual.htm

**Comment by vd1** [comment]
nice to have an html version! but fig 6.3 is a bit smallish.
Vincent

**Comment by feret** [comment]
I have updated it in the the KaSim/man version. 
I passed the fig to 15cm instead of 6cm, and put the figure with the flag [p] so that the pdf version is not too strange. 
If you find other not so beautiful things, feel free to update the tex file.  It is the same as for the .pdf version, and it is compiled into html by using 
~/KaSim$ make doc_html

Unfortunately, the html generator is a bit less convenient than the pdf one for image. 
It is important to give both the native sizes, and the expected size for each image.
